name: Deploy to AWS

on:
  push:
    branches:
      - main  # 任意のブランチでOK
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CHANNEL_SECRET_PARAM_NAME: ${{ vars.CHANNEL_SECRET_PARAM_NAME }}
      CHANNEL_ACCESS_TOKEN_PARAM_NAME: ${{ vars.CHANNEL_ACCESS_TOKEN_PARAM_NAME }}
      OPENAI_API_KEY_PARAM_NAME: ${{ vars.OPENAI_API_KEY_PARAM_NAME }}
      EMAIL_ADDRESS: ${{ vars.EMAIL_ADDRESS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Bootstrap CDK (if first time)
        run: cdk bootstrap

      - name: Build TypeScript code
        run: npm run build

      - name: Synthesize CloudFormation template
        run: cdk synth

      - name: Deploy to AWS
        run: cdk deploy --require-approval never

      - name: Garbage collect old CDK assets
        run: cdk gc --unstable=gc --confirm false