name: Node.js CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CHANNEL_SECRET_PARAM_NAME: ${{ vars.CHANNEL_SECRET_PARAM_NAME }}
      CHANNEL_ACCESS_TOKEN_PARAM_NAME: ${{ vars.CHANNEL_ACCESS_TOKEN_PARAM_NAME }}
      OPENAI_API_KEY_PARAM_NAME: ${{ vars.OPENAI_API_KEY_PARAM_NAME }}
      GEMINI_API_KEY_PARAM_NAME: ${{ vars.GEMINI_API_KEY_PARAM_NAME }}
      EMAIL_ADDRESS: ${{ vars.EMAIL_ADDRESS }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      - uses: flatt-security/setup-takumi-guard-npm@v1
      - run: npm ci
      - run: npm test
